spring:
  application:
    name: invesco-fintech
  main:
    banner-mode: off
#database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/invesco-fintech
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#security configuration
  security:
    user:
      name: admin
      password: f508aebb

  liquibase:
    #it is working with liquibase without enabled
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

#port configuration
server:
  port: 8686

#logging configuration
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        sql: DEBUG
    com:
      invesco_fintech: DEBUG

#JWT configuration
#spring.app.jwtSecret        = secretKey0666aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
#spring.app.jwtExpirationMs  = 3000000